### ISSUE TITLE
Cannot add members to a collection based on username search

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/ckanext-dcor_schemas#28]
I go into a collection, click on "Manage", then "Members" and click on "Add Member". There I have two options: search for an existing user or invite a user via email. If I chose the username option and start typing in a name of a person or a username, there are no suggestions and I don't know if the username actually exists on DCOR, until I click on "Add Member" in the bottom right. In case the user doesn't exist yet, I will get an error telling me "{'Username': 'Not found: User'}". In case the username actually exists, the person is of course added.

But this means, unless I know the usernames of the users I want to add to the collection, I cannot add them because it would be a guessing game.

Expected behavior: When I start typing, suggestions for usernames should pop up. In the ideal case, the real and full name and not the DCOR username (which is sometimes just the first name or maybe first letter of the first name plus the sure name).

**Comment by B-Hartmann** [comment]
Right now, I cannot add users at all. Was there in the meantime an update of the DCOR server that changed something regarding member handling?

**Comment by B-Hartmann** [comment]
This affects not only circles, but also collections.

**Comment by paulmueller** [comment]
This sounds like a bug. I will probably not have time to look into this in the near future.

**Comment by PinkShnack** [comment]
+1 for this.

Might be related: I tried to add a new member to a circle. If the "username" dropdown menu appears, I can't add the new user. However, If I stop the webpage from fully loading, then I can type the name in and add the new user. Funky stuff!

**Comment by paulmueller** [comment]
I tracked this down to a too strict nginx configuration.
